libname data '/folders/myfolders/BIOS669/Final/Data';


FILENAME REFFILE '/folders/myfolders/BIOS669/Final/R_files/tot1979.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.SAS1979;
	GETNAMES=YES;
RUN;



FILENAME REFFILE '/folders/myfolders/BIOS669/Final/R_files/tot1983.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.SAS1983;
	GETNAMES=YES;
RUN;



FILENAME REFFILE '/folders/myfolders/BIOS669/Final/R_files/tot1987.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.SAS1987;
	GETNAMES=YES;
RUN;




FILENAME REFFILE '/folders/myfolders/BIOS669/Final/R_files/tot1991.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.SAS1991;
	GETNAMES=YES;
RUN;



FILENAME REFFILE '/folders/myfolders/BIOS669/Final/R_files/tot1995.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.SAS1995;
	GETNAMES=YES;
RUN;


FILENAME REFFILE '/folders/myfolders/BIOS669/Final/R_files/tot1999.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.SAS1999;
	GETNAMES=YES;
RUN;

FILENAME REFFILE '/folders/myfolders/BIOS669/Final/R_files/tot2003.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.SA2003;
	GETNAMES=YES;
RUN;

FILENAME REFFILE '/folders/myfolders/BIOS669/Final/R_files/tot2007.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.SAS2007;
	GETNAMES=YES;
RUN;

FILENAME REFFILE '/folders/myfolders/BIOS669/Final/R_files/tot2011.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.SAS2011;
	GETNAMES=YES;
RUN;

FILENAME REFFILE '/folders/myfolders/BIOS669/Final/R_files/tot2015.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.SAS2015;
	GETNAMES=YES;
RUN;

FILENAME REFFILE '/folders/myfolders/BIOS669/Final/R_files/tot2019.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATA.SAS2019;
	GETNAMES=YES;
RUN;






















